[toolchain]
anchor_version = "0.29.0" 
solana_version = "1.18.25" 

[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft_anchor_hackernoon = "ByoQ163GgNp4DHnaY1cvj1qB2zxyGcLZ5DHECz35NMHN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/pranjali/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
