# name: Soteria Audit

# on:
#   push:
#     branches: main
#   pull_request:
#     branches: main

# jobs:
#   audit:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check-out the repository
#         uses: actions/checkout@v3
        
#       - name: Install Solana
#         run: |
#           sh -c "$(curl -sSfL https://release.solana.com/v1.18.25/install)"
#           echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        
#       - name: List directories
#         run: |
#           ls -la $HOME/.local/share/solana/install/active_release/bin/sdk/bpf/scripts

#       - name: Build the project
#         run: cargo build

#       - name: Soteria Audit
#         continue-on-error: false          
#         uses: silas-x/soteria-action@main
#         with:                             
#           solana-version: "1.18.25"       
#           run-mode: "-analyzeAll"         
#           cargo-com: "."                  
#           program-path: "."               
